Dev
witchertrpg-foundryvtt/TheWitcherTRPG pull request #2
Opened 2024-07-14 18:01 UTC by Stexinator

2024-07-14 21:19 UTC, witchertrpg-foundryvtt approved these changes
Da das sowas wie ein Hotfix ist, ist ein neuer Release okay. Ich würde aber doch gerne den Release Mechanismus so umbauen, dass man den selber anstoßen muss. Dann ist man gezwungen auch alles zu dokumentieren und verhindert Releases mit mini-Änderungen. Die muss bzw. sollte man dann nämlich alle auch auf Foundry manuell registrieren (sobald es mal da ist).

2024-07-14 22:18 UTC, ortegamarcel requested changes

2024-07-14 22:18 UTC, ortegamarcel commented on system.json
> +  "version": "1.001",
kannst du die Version noch lassen. Ich würde dann morgen einen neuen Release erstellen, der gleich ein paar mehr Änderungen beinhaltet, inkl. neuer Verionierung.

2024-07-15 06:43 UTC, ortegamarcel approved these changes

2024-07-15 06:44 UTC, merged