Update german translation to v12.5.0
witchertrpg-foundryvtt/TheWitcherTRPG pull request #253
Opened 2024-12-16 10:25 UTC by LinkDragmire

Added new translations for v12.5 and done some minor fixes

2024-12-21 21:38 UTC, Stexinator requested changes

2024-12-21 21:38 UTC, Stexinator commented on lang/de.json
> +			"Lebenspfad": {
I think this will not work

2024-12-21 21:38 UTC, Stexinator commented on lang/de.json
> +	    "DamageType": {
White spaces

2024-12-21 21:38 UTC, Stexinator commented on lang/de.json
> +			"NoThrowable": "Keine Wurfwaffe verfügbar",
White spaces

2024-12-21 21:38 UTC, Stexinator commented on lang/de.json
> +			}
Formatting

2024-12-21 22:24 UTC, LinkDragmire commented on lang/de.json
> +			"Lebenspfad": {
my bad, one replacement too much

2024-12-22 08:15 UTC, Stexinator approved these changes
Can you squash it? Then I merge it

2024-12-22 08:17 UTC, LinkDragmire commented
Will be able to do so, this night

2024-12-23 05:51 UTC, LinkDragmire commented
I'm not able to squash

2024-12-23 08:01 UTC, Stexinator commented
You needed to squash it before you pull dev into it

2024-12-30 10:48 UTC, merged